plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vslauncher'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vslauncher'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '0.6.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        benchmark {
            initWith release
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
            debuggable false
        }

        baselineProfile {
            initWith release
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
            matchingFallbacks = ['release']
            debuggable false
        }
    }

    buildFeatures {
        buildConfig false
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    benchmarkImplementation 'androidx.profileinstaller:profileinstaller:1.4.1'
    baselineProfileImplementation 'androidx.profileinstaller:profileinstaller:1.4.1'
}
